bankproject/bankproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include(('transactions.urls', 'transactions'), namespace='transactions')),
    path('auth/', include(('users.urls', 'authenticating'), namespace='authenticating')),
    path('', include(('core.urls', 'core'), namespace='core')),
   
]

bankproject/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.home, name='home'),
    
    path('why_rbs_international/', views.why_rbs_international, name='why_rbs_international'),
    path('corporate_service_providers/', views.corporate_service_providers, name='corporate_service_providers'),
    path('real_estate_finance/', views.real_estate_finance, name='real_estate_finance'),
    path('private_equity/', views.private_equity, name='private_equity'),
    path('asset_management/', views.asset_management, name='asset_management'),
    path('private_debt/', views.private_debt, name='private_debt'),
    path('infrastructure_renewables/', views.infrastructure_renewables, name='infrastructure_renewables'),
    path('where_we_are/', views.where_we_are, name='where_we_are'),
    path('jersey/', views.jersey, name='jersey'),
    path('guernsey/', views.guernsey, name='guernsey'),
    path('gibraltar/', views.gibraltar, name='gibraltar'),
    path('isle_of_man/', views.isle_of_man, name='isle_of_man'),
    path('luxembourg/', views.luxembourg, name='luxembourg'),
    path('london/', views.london, name='london'),
    path('what_we_do/', views.what_we_do, name='what_we_do'),
    path('bank_accounts_overdrafts/', views.bank_accounts_overdrafts, name='bank_accounts_overdrafts'),
    path('cash_management/', views.cash_management, name='cash_management'),
    path('cards_payments/', views.cards_payments, name='cards_payments'),
    path('financing/', views.financing, name='financing'),
    path('sustainable_finance/', views.sustainable_finance, name='sustainable_finance'),
    path('depositary_services/', views.depositary_services, name='depositary_services'),
    path('markets/', views.markets, name='markets'),
    path('foreign_exchange/', views.foreign_exchange, name='foreign_exchange'),
    path('money_market_deposits/', views.money_market_deposits, name='money_market_deposits'),
    path('notice_deposits/', views.notice_deposits, name='notice_deposits'),
    path('insights/', views.insights, name='insights'),
    path('news/', views.news, name='news'),
    path('eq_digital_banking', views.eq_digital_banking, name='eq_digital_banking'),
    path('eq_online_banking/', views.eq_online_banking, name='eq_online_banking'),
    path('eq_mobile/', views.eq_mobile, name='eq_mobile'),
    path('eq_account_opening/', views.eq_account_opening, name='eq_account_opening'),
    path('eq_support_centre/', views.eq_support_centre, name='eq_support_centre'),
    path('smartcard_and_reader_support_for_eq/', views.smartcard_and_reader_support_for_eq, name='smartcard_and_reader_support_for_eq'),
    path('help_support/', views.help_support, name='help_support'),
    path('fraud_security/', views.fraud_security, name='fraud_security'),
    path('debit_card_payment_support/', views.debit_card_payment_support, name='debit_card_payment_support'),
    path('report_a_fraud_or_scam/', views.report_a_fraud_or_scam, name='report_a_fraud_or_scam'),
    path('corporate_account_reclaims/', views.corporate_account_reclaims, name='corporate_account_reclaims'),
    path('make_a_change_to_your_account/', views.make_a_change_to_your_account, name='make_a_change_to_your_account'),
    path('results_centre/', views.results_centre, name='results_centre'),
    path('bank_base_rate/', views.bank_base_rate, name='bank_base_rate'),
    path('key_information_document_for_priips', views.key_information_document_for_priips, name='key_information_document_for_priips'),
    path('how_automatic_exchange_of_tax_information_affects_you/', views.how_automatic_exchange_of_tax_information_affects_you, name='how_automatic_exchange_of_tax_information_affects_you'),
    path('account_fees_and_charges/', views.account_fees_and_charges, name='account_fees_and_charges'),
    path('payment_services_directive2/', views.payment_services_directive2, name='payment_services_directive2'),
    path('luxembourg_intermediate_ownership_changes/', views.luxembourg_intermediate_ownership_changes, name='luxembourg_intermediate_ownership_changes'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('how_to_make_a_complaint/', views.how_to_make_a_complaint, name='how_to_make_a_complaint'),
    path('leave_us_feedback/', views.leave_us_feedback, name='leave_us_feedback'),
    path('nominate_a_member_of_staff/', views.nominate_a_member_of_staff, name='nominate_a_member_of_staff'),
    
    
    
    
]

bankproject/transactions/urls.py
from django.urls import path
from . import views


app_name = 'transactions'

urlpatterns = [
    path('pat/', views.pat, name='pat'),
    path('make-payment/', views.make_payment, name='make_payment'),
    path('verify-transaction/', views.verify_transaction, name='verify_transaction'),
    path('transactions/', views.transaction_list, name='transaction_list'),
    path('receipt/<uuid:receipt_id>/', views.display_receipt, name='display_receipt'),



]

bankproject/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    path('register/', views.register_step1, name='register_step1'),
    path('register/step2/', views.register_step2, name='register_step2'),
    path('register/step3/', views.register_step3, name='register_step3'),
    path('register/step4/', views.register_step4, name='register_step4'),
    
    
    path('login/', views.user_login, name='login'),
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.home, name='home'),
    path('account/<int:account_id>/transactions/', views.account_transactions, name='account_transactions'),
    path('account/<int:account_id>/transactions/download/', views.download_transactions_csv, name='download_transactions_csv'),
    #path('account/<int:account_id>/transactions/download_pdf/', views.download_transactions_pdf, name='download_transactions_pdf'),
]

bankproject/accounts/models.py
from django.db import models
from django.contrib.auth.models import User




class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_number = models.CharField(max_length=20, unique=True)
    account_type = models.CharField(max_length=20)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{str(self.balance)} - {self.account_type} - {self.account_number}"

bankproject/users/models.py
from django.db import models
from django.contrib.auth.models import User

class CustomerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    customer_type = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField()
    postcode = models.CharField(max_length=10, blank=True, null=True)
    business_postcode = models.CharField(max_length=10, blank=True, null=True)
    customer_number = models.CharField(max_length=10, unique=True)
    pin = models.CharField(max_length=4)

    def __str__(self):
        return f"{self.user.username}'s Profile"

bankproject/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from accounts.models import Account
from transactions.models import Transaction
from django.contrib.auth.models import User
from .forms import CustomerTypeForm, PersonalCustomerForm, BusinessCustomerForm, CreditCardCustomerForm, MortgageCustomerForm, AccountSetupForm, PinPasswordForm
import random
from .models import CustomerProfile
from django.contrib import messages
from django.utils import timezone
from decimal import Decimal
import csv
from django.http import HttpResponse
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image
from reportlab.lib.units import inch
import io

from reportlab.lib.utils import ImageReader


def register_step1(request):
    if request.method == 'POST':
        form = CustomerTypeForm(request.POST)
        if form.is_valid():
            customer_type = form.cleaned_data['customer_type']
            request.session['customer_type'] = customer_type
            return redirect('register_step2')
    else:
        form = CustomerTypeForm()
    return render(request, 'users/register_step1.html', {'form': form})


def register_step2(request):
    customer_type = request.session.get('customer_type')
    if customer_type == 'personal':
        form_class = PersonalCustomerForm
    elif customer_type == 'business':
        form_class = BusinessCustomerForm
    elif customer_type == 'credit_card':
        form_class = CreditCardCustomerForm
    elif customer_type == 'mortgage':
        form_class = MortgageCustomerForm
    else:
        return redirect('register_step1')

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            customer_info = form.cleaned_data
            # Convert date to string
            if 'date_of_birth' in customer_info:
                customer_info['date_of_birth'] = customer_info['date_of_birth'].isoformat()
            request.session['customer_info'] = customer_info
            return redirect('register_step3')
    else:
        form = form_class()
    return render(request, 'users/register_step2.html', {'form': form})



def register_step3(request):
    if request.method == 'POST':
        form = AccountSetupForm(request.POST)
        if form.is_valid():
            request.session['account_setup'] = form.cleaned_data
            if form.cleaned_data['know_pin'] == 'yes':
                return redirect('register_step4')
            else:
                return redirect('register_step4')
                # Handle the case where the user doesn't know their PIN
                pass
    else:
        customer_number = ''.join([str(random.randint(0, 9)) for _ in range(10)])
        form = AccountSetupForm(initial={'customer_number': customer_number})
    return render(request, 'users/register_step3.html', {'form': form})

def register_step4(request):
    if request.method == 'POST':
        form = PinPasswordForm(request.POST)
        if form.is_valid():
            customer_info = request.session['customer_info']
            account_setup = request.session['account_setup']
            email = customer_info['email']
            password = form.cleaned_data['password']
            customer_number = account_setup['customer_number']




            # Create user account
            user = User.objects.create_user(
                username=customer_number,  
                email=email,
                password=password
            )
            user.first_name = customer_info['first_name']
            user.last_name = customer_info['last_name']
            user.save()


            # Create customer profile
            CustomerProfile.objects.create(
                user=user,
                customer_type=request.session['customer_type'],
                middle_name=customer_info.get('middle_name'),
                date_of_birth=customer_info['date_of_birth'],
                postcode=customer_info.get('postcode'),
                business_postcode=customer_info.get('business_postcode'),
                customer_number=account_setup['customer_number'],
                pin=form.cleaned_data['pin']
            )
            
            
            # Create savings and current accounts
            Account.objects.create(
                user=user,
                account_number=''.join([str(random.randint(0, 9)) for _ in range(10)]),
                account_type='Savings',
                balance=0.00
            )
            Account.objects.create(
                user=user,
                account_number=''.join([str(random.randint(0, 9)) for _ in range(10)]),
                account_type='Current',
                balance=0.00
            )

            login(request, user)
            return redirect('dashboard')
    else:
        form = PinPasswordForm()
    return render(request, 'users/register_step4.html', {'form': form})


def user_login(request):
    if 'step' in request.GET and request.GET['step'] == '2':
        if request.method == 'POST':
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('authenticating:dashboard')
            else:
                return render(request, 'users/login2.html', {'error': 'Invalid email or password'})
        return render(request, 'users/login2.html')
    else:
        return render(request, 'users/login.html')




'''def user_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard')
        else:
            return render(request, 'users/login.html', {'error': 'Invalid email or password'})
    return render(request, 'users/login.html')

'''


@login_required
def dashboard(request):
    user = request.user
    accounts = Account.objects.filter(user=user)
    last_login = user.last_login
    
    if request.method == 'POST':
        from_account = Account.objects.get(id=request.POST['from_account'])
        to_account_number = request.POST['to_account']
        #amount = float(request.POST['amount'])
        amount = Decimal(request.POST['amount'])

        try:
            to_account = Account.objects.get(account_number=to_account_number)
        except Account.DoesNotExist:
            messages.error(request, 'Recipient account not found.')
            return redirect('dashboard')

        if from_account.balance >= amount:
            from_account.balance -= amount
            to_account.balance += amount
            from_account.save()
            to_account.save()

            Transaction.objects.create(
                account=from_account,
                amount=amount,
                transaction_type='Debit',
                description=f'Transfer to account {to_account.account_number}',
                timestamp=timezone.now()
            )

            # Create a corresponding transaction for the receiving account
            Transaction.objects.create(
                account=to_account,
                amount=amount,
                transaction_type='Credit',
                description=f'Received from account {from_account.account_number}',
                timestamp=timezone.now()
            )

            messages.success(request, 'Transfer successful!')
        else:
            messages.error(request, 'Insufficient funds.')

    context = {
        'accounts': accounts,
        'last_login': last_login,
    }
    
    return render(request, 'users/dashboard.html', context)



@login_required
def account_transactions(request, account_id):
    account = get_object_or_404(Account, id=account_id, user=request.user)
    transactions = Transaction.objects.filter(account=account).order_by('-timestamp')

    context = {
        'account': account,
        'transactions': transactions,
    }

    return render(request, 'users/account_transactions.html', context)



@login_required
def download_transactions_csv(request, account_id):
    account = get_object_or_404(Account, id=account_id, user=request.user)
    transactions = Transaction.objects.filter(account=account).order_by('-timestamp')

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="transactions_{account.account_number}.csv"'

    writer = csv.writer(response)
    writer.writerow(['Date', 'Description', 'Amount', 'Type'])

    for transaction in transactions:
        writer.writerow([transaction.timestamp, transaction.description, transaction.amount, transaction.transaction_type])

    return response


'''
@login_required
def download_transactions_pdf(request, account_id):
    account = get_object_or_404(Account, id=account_id, user=request.user)
    transactions = Transaction.objects.filter(account=account).order_by('-timestamp')

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="transactions_{account.account_number}.pdf"'

    # Create the PDF object using ReportLab
    doc = SimpleDocTemplate(response, pagesize=A4)
    elements = []

    # Convert SVG to PNG
    svg_path = "static/img/logo1.svg"
    png_image = io.BytesIO()
    cairosvg.svg2png(url=svg_path, write_to=png_image)
    png_image.seek(0)
    logo = Image(ImageReader(png_image), width=2 * inch, height=2 * inch)
    logo.hAlign = 'LEFT'

bankproject/users/templates/users/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digital Banking - Account Summary</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.svg' %}">
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
        }
        .main-menu {
            background-color: #162159;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 20px;
        }
        .logo {
            color: white;
        }
        .logout-btn {
            background-color: #FF1493;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }
        .container {
            display: flex;
        }
        .sidebar {
            width: 250px;
            
            padding: 20px;
        }
        .sidebar h2 {
            color: #162159;
        }
        .sidebar-menu {
            list-style-type: none;
            padding: 0;
        }
        .sidebar-menu li a {
            color: #FF1493;
            text-decoration: none;
            
        }
        .sidebar-menu li {
            padding-bottom: 10px;
        }
        .main-content {
            flex: 1;
            padding: 20px;
        }
        .account-card {
            border: 1px solid #ddd;
            margin-bottom: 20px;
        }
        .account-card-header {
            background-color: #162159;
            color: white;
            padding: 10px;
        }
        .account-card-body {
            display: flex;
            justify-content: space-between;
            padding: 10px;
        }
        .account-card-footer {
            background-color: #f1f1f1;
            padding: 10px;
        }
        .account-card-footer a {
            color: #FF1493;
            text-decoration: none;
            margin-right: 10px;
        }
        .savings-goal-card {
            background-color: #162159;
            color: white;
            padding: 20px;
            margin-top: 20px;
        }
        @media (max-width: 768px) {
            .container {
                flex-direction: column;
            }
            .sidebar {
                width: 100%;
            }
        }

        .quick-transfer-form {
            display: flex;
            flex-direction: column;
            gap: 10px;
            margin-top: 20px;
        }
        
        .form-select, .form-input {
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        
        .form-button {
            background-color: #1c7430;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 4px;
            cursor: pointer;
        }
        
        .form-button:hover {
            background-color: #34ce57;
        }


        .container {
            display: flex;
            flex-wrap: wrap;
        }

        .products-sidebar {
            width: 200px;
            padding: 20px;
            background-color: #f8f9fa;
        }

        .product-list {
            list-style-type: none;
            padding-left: 0;
        }

        .product-list li::before {
            content: "➔";
            color: #FF1493;
            margin-right: 5px;
        }

        @media (max-width: 768px) {
            .products-sidebar {
                width: 100%;
                order: 1;
            }
            
            .main-content {
                order: 0;
            }
        }

        .tiny-icon {
            width: 50px;
            height: 50px;
            vertical-align: middle;
            margin-right: 5px;
        }


        .account-info {
            display: flex;
            align-items: center;
        }
        
        .account-icon {
            width: 50px;
            height: 50px;
            margin-right: 8px; /* Reduced margin to bring them closer */
        }
        
        .balance-info {
            display: flex;
            align-items: center;
        }
        
        .fa-info-circle {
            font-size: 25px;
            color: #FF1493;
            margin-right: 10px;
        }
        
        .balance-amount {
            font-weight: bold;
            font-size: 24px;
        }
        
        a {
            text-decoration: none;
        }
        
        
    </style>
</head>
<body>
    <div class="main-menu">
        <div class="logo">
            <img src="{% static 'img/logo1.svg' %}" width="70"  alt="Account">
        </div>
        <button class="logout-btn"><a href="{% url 'authenticating:logout' %}">Logout</a></button>
    </div>
    <div class="container">
        <div class="sidebar">
            <h2>Digital Banking</h2>
            <ul class="sidebar-menu">
                <li><a href="#">Account Summary</a></li>
                <li><a href="{% url 'transactions:pat' %}">Payments and Transfer</a></li>
                <li><a href="{% url 'transactions:transaction_list' %}">Statements</a></li>
                <li><a href="#">Mailbox</a></li>
                <li><a href="#">Paperless Settings</a></li>
                <li><a href="#">Alerts</a></li>
                <li><a href="#">Cards</a></li>
                <li><a href="#">Your Details</a></li>
                <li><a href="#">Security</a></li>
                <li><a href="#">Log out</a></li>
            </ul>
            
            
            <form method="post" class="quick-transfer-form">
                {% csrf_token %}
                <select name="from_account" class="form-select">
                    {% for account in accounts %}
                        <option value="{{ account.id }}">{{ account.account_number }} - {{ account.account_type }}</option>
                    {% endfor %}
                </select>
                <input type="text" name="to_account" placeholder="Enter account number" class="form-input">
                <input type="number" name="amount" step="0.01" min="0" placeholder="Enter amount" class="form-input">
                <button type="submit" class="form-button">Transfer</button>
            </form>



            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}




        </div>
        <div class="main-content">
            <h1 style="color: #162159;">Account Summary</h1>
            <p>Customer number: {{ user.username }}</p>
            <p>Last login: {{ last_login }}<!-- Fetch last login time --></p>
            <h3 style="color: #162159;">Personal Accounts</h3>
            <!-- Loop through user's accounts -->
            {% for account in user.account_set.all %}
            <div class="account-card">
                
                <div class="account-card-body">
                    <div>
                       
                        <div class="account-info">
                            <img src="{% static 'img/logo.svg' %}" alt="Account" class="account-icon">
                            <h3>A/C: {{ account.account_number }}</h3>
                        </div>

                        <p>Account Type: {{ account.account_type }}</p>
                    </div>
                    <div class="balance-info">
                        <i class="fas fa-info-circle fa-5x"></i>
                        <span class="balance-amount">€ {{ account.balance }}</span>
                    </div>
                    
                </div>
                <div class="account-card-footer">
                    <a href="{% url 'transactions:make_payment' %}" style="color: #FF1493;">Make a Payment</a>
                    <a href="#" style="color: #FF1493;">View Account Details</a>
                    <a href="{% url 'authenticating:account_transactions' account.id %}" style="color: #FF1493;">View Transactions</a>
                </div>
            </div>
            {% endfor %}




            <div class="savings-goal-card">
                <h3>Saving Goals</h3>
                <p>Want to save for that special something? Why not let us help you with our Savings Goal tool which has been rated 5 star by the FairBanking Foundation</p>
                <button class="form-button">Find Out More</button>
            </div>
        </div>

        <div class="products-sidebar">
            <h3 style="color: #162159;">Our Products</h3>
            <h5 style="color: #162159;">Personal Products</h5>
            <ul class="product-list">
                <li>Savings accounts</li>
                <li>Cash ISAs</li>
                <li>Current accounts</li>
                <li>Upgrade your account</li>
                <li>Credit cards</li>
                <li>Overdrafts</li>
                <li>Loans</li>
                <li>Mortgages</li>
                <li>Insurance</li>
                <li>Travel money</li>
                <li>Investment products</li>
                <li>Mobile app</li>
                <li>What's new</li>
            </ul>
        </div>


    </div>
</body>
</html>

bankproject/users/templates/users/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Our Bank</title>
</head>
<body>
    <h1>Welcome to Our Bank</h1>
    <p>Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'register' %}">register</a> to continue.</p>
</body>
</html>

bankproject/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
    <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
</body>
</html>

bankproject/users/templates/users/register_step1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Step 1: Choose Customer Type</title>
</head>
<body>
    <h1>Step 1: Choose Customer Type</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

bankproject/users/templates/users/register_step2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Step 2: Personal Information</title>
</head>
<body>
    <h1>Step 2: Personal Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

bankproject/users/templates/users/register_step3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Step 3: Account Setup</title>
</head>
<body>
    <h1>Step 3: Account Setup</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

bankproject/users/templates/users/register_step4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Step 4: Set PIN and Password</title>
</head>
<body>
    <h1>Step 4: Set PIN and Password</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Complete Registration</button>
    </form>
</body>
</html>